name: Arduino Smoke Tests

on:
  - push
  - pull_request

jobs:
  compile-led-matrix-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "adafruit:samd:adafruit_metro_m0"
          platforms: |
            - name: "adafruit:samd"
              source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
          sketch-paths: |
            - arduino_src/led_matrix_controller
          libraries: |
            - name: "Adafruit Protomatter"

  compile-led-pwm-driver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:megaavr:nona4809"
          sketch-paths: |
            - arduino_src/led_pwm_driver
